# ===============================================================
# Filename: Makefile
# -------------------------------
# Copyright(C),
# Author: zhenquan.qiu
# Version: V1.0.0
# Last modified: 24/08 2017 23:10
# Description:
#
# Change Log:
# NO.	Author		    Date		Modified
# 00	zhenquan.qiu	24/08 2017
# ===============================================================



all:
	gcc -c hello.c -I.
	ar rcsv libhello.a hello.o


clean:
	rm -rf hello.o
	rm -rf libhello.a
