# ===============================================================
# Filename: Makefile
# -------------------------------
# Copyright(C),
# Author: zhenquan.qiu
# Version: V1.0.0
# Last modified: 24/08 2017 23:13
# Description:
# 
# Change Log:
# NO.	Author		    Date		Modified
# 00	zhenquan.qiu	24/08 2017
# ===============================================================


static:
	gcc -o main test-hello.c -L./hello-static -lhello -I./hello-static

dynamic:
	gcc -o main test-hello.c -L./hello-dynamic -lhello -I./hello-dynamic

clean:
	rm -rf main

